# Uncomment the next line to define a global platform for your project
 platform :ios, '15.5'

target 't-softProjectAlamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for t-softProjectAlamofire
pod 'Alamofire'
end
